apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:            # bellong to the RS itself
    app: nginx-rs
  name: rs-name      # name os RS
spec:
  replicas: 1        #only one pod
  selector:          # select the pod by this label >>> must match with the pod label, if is not matching it not gonna create
    matchLabels:
      app: nginx-replicaset
  template:
    metadata:
      labels:
        app: nginx-replicaset    # pod label 
    spec:
      containers:
      - image: nginx:1.13
        name: rs-name-container

