apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc     # name of RC
spec:
  replicas: 3       #will create 3 pod at ones
  selector:
    app: nginx-rc-pod
  template:        # template for the pod
    metadata:
      labels:             # labels are very important
        app: nginx-rc-pod    
    spec:
     containers:
     - name: nginx-replicationcontroller
       image: nginx
