apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  labels:
    app: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rs-pod   # select the pods by this labe;
  template:
    metadata:
      labels:
        app: mysql-rs-pod   #should match labels
    spec:
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc  
      containers:
      - name: mysql
        image: mysql:5.6
        env:
          # Test, use secret in prod
        - name: MYSQL_ROOT_PASSWORD
          value: #atache pass
        livenessProbe:
          tcpSocket:   #check if port 3306 is working, ifnot will restart the pod
            port: 3306
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/mysql #it will mount volume from the Persistent Volume Claim
