apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-pod
    run: nginx
    team: dev-ops
    department: devops
  name: nginx
  namespace: default
spec:
  containers:
  - image: nginx
    name: nginx
