apiVersion: v1
kind: Pod               # A pod can have multiple containers 
metadata:
  name: web1           # name of my pod
  namespace: default
spec:                  #what container you want to creat
  containers:
  - image: httpd       #image of the container
    name: web         # name of the container
